trigger:
- main

pool:
  name: ADO
  vmImage: 'windows-latest'
  demands: 
    - Agent.Name -equals ADO2 # Change to your agent pool
    
variables:
- group: VM  # Link to the Variable Group

stages:
- stage: FetchIPConfig
  jobs:
  - job: RunIPConfig
    steps:
    - checkout: self

    - task: PowerShell@2
      displayName: "Run Get-IPConfig Script"
      inputs:
        targetType: "inline"
        script: |
          & "$(Build.SourcesDirectory)/CreateAppPool_Remote1.ps1" -TargetServer $(targetServer) -UserName $(userName) -Password $(password)

    - task: PublishBuildArtifacts@1
      displayName: "Publish IP Config Output"
      inputs:
        pathToPublish: "C:\\ADO2\\ipconfig_output_$(targetServer).txt"
        artifactName: "IPConfigReport"
