trigger: 

- main
pool:
  name: ADO
  vmImage: 'windows-latest'
steps:

  
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      # Automate yes/no prompts
      $command = "Some-Command"
      
      # Using echo to send yes response
      echo "[FINGERPRINT]" | & $command
      # PASSWORD
      echo "9403" | & $command
