trigger: 

- main
pool:
  name: ADO
  vmImage: 'windows-latest'
steps:

  
# - task: PowerShell@2
#   inputs:
#     targetType: 'inline'
#     script: |
#       # Write your PowerShell commands here.
      
#       # Automate yes/no prompts
#       - task: DownloadSecureFile@1
#         inputs:
#           secureFile: 'id_rsa'
#           socketTimeout: '200'
       
#        ssh -l $(private-key) shubham@DESKTOP-8R1FA
- task: InstallSSHKey@0
  displayName: 'Install an SSH key'
  inputs:
    knownHostsEntry: 'SHA256:wzvCNBYYki1s1EHnzCKO1tyhuNnETeZXOBcBPhRWOX0 shubham@DESKTOP-8R1FAH3'
    sshPublicKey: '$(myPubKey)'
    sshKeySecureFile: 'id_rsa'

      
      # # Using echo to send yes response
      # echo "[FINGERPRINT]" | & $command
      # # PASSWORD
      # echo "9403" | & $command
      # Define your SSH credentials
      #  $host = "DESKTOP-8R1FAH3"
      #  $username = "shubham"
      #  $password = "9403"  # Use PowerShell's SecureString for better security
       
      #  # Convert password to a SecureString
      #  $securePassword = ConvertTo-SecureString $password -AsPlainText -Force
       
       # Create a PSCredential object using the username and secure password
      

