trigger: 

- main
# pool:
#   name: ADO
#   vmImage: 'windows-latest'

# jobs:
# - job: Deploy
#   steps:
#   - task: SSH@0
#     inputs:
#       sshEndpoint: 'openSSH'
#       runOptions: 'commands'
#       commands: |
#         echo "Deploying code via SSH"
#         # Copy files, restart services, or execute commands on the Windows VM
#   displayName: 'Deploy to Windows VM via SSH'


jobs:
  - job: SSHCommand
    pool:
      name: ADO
      vmImage: 'windows-latest'

    steps:
      - script: |
          $username = 'shubham'
          $hostname = 'DESKTOP-8R1FAH3'
          $password = '9403'  # Consider using a secure method to handle this

          # Create the SSH command
          $command = "ssh -o StrictHostKeyChecking=no $username@$hostname 'echo \"hello shubham\"'"

          # Execute the command
          Invoke-Expression $command
        displayName: 'Run SSH Command'


     

    
