trigger: 

- main
pool:
  name: ADO
  vmImage: 'windows-latest'

steps:
- task: InstallSSHKey@0
  displayName: 'Install an SSH key'
  inputs:
    knownHostsEntry: 'shubham@DESKTOP-8R1FAH3'
    sshPublicKey: '$(myPubKey)'
    sshKeySecureFile: 'id_rsa'


