trigger: 

- main
pool:
  name: ADO
  vmImage: 'windows-latest'

jobs:
- job: Deploy
  steps:
  # - task: SSH@0
  #   inputs:
  #     sshEndpoint: 'Shubham-ssh'
  #     runOptions: 'commands'
  #     commands: |
  #       echo "Deploying code via SSH"
  #       # Copy files, restart services, or execute commands on the Windows VM
  # displayName: 'Deploy to Windows VM via SSH'
  # - task: SSH@0
  #   inputs:
  #       sshEndpoint: 'Shubham-ssh'
  #       runOptions: 'commands'
  #       commands: 'echo "deployt the code"'
  #       readyTimeout: '20000'
  #       args: 
    
    # - task: PowerShellOnTargetMachines@3
    #   inputs:
    #    Machines: '172.27.194.20'
    #    UserName: 'Desktop-8r1fah3\shubham'
    #    UserPassword: '9403'
    #    InlineScript: |
    #      # Write your powershell commands here.
      
    #      Write-Output "Hello World"

     - task: WindowsMachineFileCopy@2
       inputs:
         SourcePath: 'D:\Password 123.txt'
         MachineNames: '172.27.194.20'
         AdminUserName: 'shubham'
         AdminPassword: '9403'
         TargetPath: 'c:\New Folder'

     

    
